### ISSUE TITLE
Nodejs8.10 is no longer supported

### ISSUE THREAD

**Issue by pdlig** [aws-samples/aws-waf-classic-workshop#20]
Hi, there's an error when deploying the stack. 

**Resource handler returned message: "The runtime parameter of nodejs8.10 is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (nodejs16.x) while creating or updating functions. (Service: Lambda, Status Code: 400**

**Comment by ctd** [comment]
Thanks for reporting this and I'm sorry we didn't get back to you when you did.

To bring some closure to this issue, we're making the decision today to archive this workshop repository and won't be making any further changes. The workshop was written AWS WAF Classic, whereas we now recommend customers use the current-generation [AWS WAF](https://aws.amazon.com/waf/) service.
